export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpg",
    username: "Safak Kocaoglu",
    online: true,
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpg",
    username: "Janell Shrum",
    online: false,
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpg",
    username: "Alex Durden",
    online: true,
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpg",
    username: "Dora Hawks",
    online: false,
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpg",
    username: "Thomas Holden",
    online: true,
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpg",
    username: "Shirley Beauchamp",
    online: false,
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpg",
    username: "Travis Bennett",
    online: true,
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpg",
    username: "Kristen Thomas",
    online: false,
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpg",
    username: "Gary Duty",
    online: true,
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpg",
    username: "Safak Kocaoglu",
    online: false,
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
    fav: false,
  },
  {
    id: 2,
    photo: "assets/post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
    fav: false,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
    fav: false,
  },
  {
    id: 4,
    photo: "assets/post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
    fav: false,
  },
  {
    id: 5,
    photo: "assets/post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
    fav: false,
  },
  {
    id: 6,
    photo: "assets/post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
    fav: false,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
    fav: false,
  },
  {
    id: 8,
    photo: "assets/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
    fav: false,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
    fav: false,
  },
  {
    id: 10,
    photo: "assets/post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
    fav: false,
  },
];
